apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumenai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumenai-api
  template:
    metadata:
      labels:
        app: lumenai-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository_api }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{- range $k, $v := .Values.api.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: lumenai-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
