
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lumenai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lumenai"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/lumenai
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION:-us-east-1}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      PYTHONPATH: "."
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        uvicorn --app-dir . backend.app.main:app --host 0.0.0.0 --port 8000
      "
    expose:
      - "8000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      VITE_API_BASE_URL: /api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  edge:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./ops/nginx-edge.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbdata:
  minio:
