"""P10: Digital Twin of SPD Operations — ORM models."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String, Text

from app.db.base import Base


class SPDWorkflowStation(Base):
    """A station in the SPD workflow."""
    __tablename__ = "spd_workflow_stations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(100), nullable=False, index=True)
    facility_id = Column(String(100), nullable=False, default="")
    station_name = Column(String(255), nullable=False)
    station_type = Column(String(100), nullable=False)  # decontamination|inspection|sterilization|storage|dispatch
    capacity = Column(Integer, nullable=False, default=10)
    current_load = Column(Integer, nullable=False, default=0)
    avg_processing_time_minutes = Column(Float, nullable=False, default=30.0)
    status = Column(String(50), nullable=False, default="active")  # active|offline|maintenance
    last_updated = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))


class InstrumentFlowRecord(Base):
    """Tracks an instrument's movement through SPD stations."""
    __tablename__ = "instrument_flow_records"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(100), nullable=False, index=True)
    facility_id = Column(String(100), nullable=False, default="")
    instrument_name = Column(String(255), nullable=False)
    instrument_id = Column(String(200), nullable=False, default="")
    from_station = Column(String(255), nullable=False, default="")
    to_station = Column(String(255), nullable=False)
    station_type = Column(String(100), nullable=False)
    arrived_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    departed_at = Column(DateTime, nullable=True)
    processing_time_minutes = Column(Float, nullable=False, default=0.0)
    outcome = Column(String(50), nullable=False, default="pending")  # pending|passed|failed|quarantined
    notes = Column(Text, nullable=False, default="")


class TwinSnapshot(Base):
    """Point-in-time snapshot of the entire SPD digital twin state."""
    __tablename__ = "twin_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(100), nullable=False, index=True)
    facility_id = Column(String(100), nullable=False, default="")
    snapshot_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    total_instruments_in_flight = Column(Integer, nullable=False, default=0)
    throughput_per_hour = Column(Float, nullable=False, default=0.0)
    bottleneck_station = Column(String(255), nullable=False, default="")
    avg_cycle_time_minutes = Column(Float, nullable=False, default=0.0)
    utilization_pct = Column(Float, nullable=False, default=0.0)
    stations_json = Column(Text, nullable=False, default="[]")
    kpis_json = Column(Text, nullable=False, default="{}")


class WhatIfScenario(Base):
    """A saved what-if simulation scenario."""
    __tablename__ = "whatif_scenarios"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(100), nullable=False, index=True)
    scenario_name = Column(String(255), nullable=False)
    description = Column(Text, nullable=False, default="")
    parameters_json = Column(Text, nullable=False, default="{}")
    result_json = Column(Text, nullable=False, default="{}")
    created_by = Column(String(100), nullable=False, default="system")
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))


class SPDAlert(Base):
    """Alerts generated by the digital twin."""
    __tablename__ = "spd_alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(100), nullable=False, index=True)
    facility_id = Column(String(100), nullable=False, default="")
    alert_type = Column(String(100), nullable=False)  # bottleneck|overload|station_offline|cycle_time_exceeded|throughput_drop
    severity = Column(String(50), nullable=False)  # low|medium|high|critical
    station_name = Column(String(255), nullable=False, default="")
    message = Column(Text, nullable=False)
    metric_value = Column(Float, nullable=False, default=0.0)
    threshold_value = Column(Float, nullable=False, default=0.0)
    acknowledged = Column(Boolean, nullable=False, default=False)
    acknowledged_by = Column(String(100), nullable=False, default="")
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    resolved_at = Column(DateTime, nullable=True)
