"""Alembic environment configuration for LumenAI.

Reads DATABASE_URL from environment — never uses hardcoded credentials.
Imports all models so autogenerate can detect schema changes.
"""
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# This migrations directory is named "alembic", same as the real library --
# running the CLI with PYTHONPATH set to the `backend/` directory (needed
# so the `app.*` imports below resolve) makes Python's import system match
# this directory as the top-level `alembic` package before the real one in
# site-packages, breaking the CLI outright ("No module named
# 'alembic.config'"). Appending the real backend path here, instead of
# requiring PYTHONPATH to include it, means the CLI can be run with no
# PYTHONPATH set at all -- avoiding that collision entirely.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Load alembic.ini logging config
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override sqlalchemy.url from DATABASE_URL environment variable
database_url = os.environ.get("DATABASE_URL")
if database_url:
    config.set_main_option("sqlalchemy.url", database_url)

# Import all models so Alembic autogenerate can detect them
# These imports register models against Base.metadata
from app.db import Base  # noqa: E402

import app.db.models  # noqa: E402, F401

# `app.db.models` only re-exports a subset of this codebase's model
# modules, and autogenerate can only see what's actually been imported
# into Base.metadata by the time this runs. This list mirrors
# `backend/tests/conftest.py::_force_import_models` exactly (same audit,
# same omissions) rather than trying to share one import list between test
# and migration tooling -- a prior version of this file only mirrored 9 of
# that function's ~66 pre-existing entries plus the newly-added ones,
# silently leaving ~119 tables (atlas_enterprise_*, beacon/catalyst/
# enterprise/forge/horizon/insight/nexus/orbit/pulse/quality/sentinel/
# vanguard_* and more) out of every autogenerated migration. Deliberately
# excluded: "app.models.tenant_membership", a dead, never-imported
# duplicate of the real `TenantMembership` already defined directly in
# `app/db/models.py` that maps a *different* schema onto the same
# `tenant_memberships` table.
import app.models.audit_log  # noqa: E402, F401
import app.models.enterprise_quality  # noqa: E402, F401
import app.models.cv_inference  # noqa: E402, F401
import app.models.alert_event  # noqa: E402, F401
import app.models.inspection  # noqa: E402, F401
import app.models.review  # noqa: E402, F401
import app.models.user  # noqa: E402, F401
import app.models.benchmarking  # noqa: E402, F401
import app.models.vendor_intelligence  # noqa: E402, F401
import app.models.tenant_plan  # noqa: E402, F401
import app.models.payment_event  # noqa: E402, F401
import app.models.predictions  # noqa: E402, F401
import app.models.regulatory  # noqa: E402, F401
import app.models.copilot  # noqa: E402, F401
import app.models.digital_twin  # noqa: E402, F401
import app.models.validation  # noqa: E402, F401
import app.models.pilot  # noqa: E402, F401
import app.models.tenant_health  # noqa: E402, F401
import app.models.tenant_subscription_p14  # noqa: E402, F401
import app.models.manufacturer_reg  # noqa: E402, F401
import app.models.usage  # noqa: E402, F401
import app.models.sso_config  # noqa: E402, F401
import app.models.network_benchmark  # noqa: E402, F401
import app.models.recall_signal  # noqa: E402, F401
import app.models.instrument_registry  # noqa: E402, F401
import app.models.baseline_library  # noqa: E402, F401
import app.models.baseline_image_library  # noqa: E402, F401
import app.models.external_connector  # noqa: E402, F401
import app.models.patient_safety  # noqa: E402, F401
import app.models.integrations  # noqa: E402, F401
import app.models.quality_intelligence  # noqa: E402, F401
import app.models.digital_quality_twin  # noqa: E402, F401
import app.models.global_intelligence  # noqa: E402, F401
import app.models.consent_record  # noqa: E402, F401
import app.models.supervisor_review  # noqa: E402, F401
import app.models.clinical_decision_ledger  # noqa: E402, F401
import app.models.cios_event  # noqa: E402, F401
import app.models.inspection_image_tag  # noqa: E402, F401
import app.models.simulation_engine  # noqa: E402, F401
import app.models.or_connect  # noqa: E402, F401
import app.models.quality_guardian  # noqa: E402, F401
import app.models.sentinel_orchestration  # noqa: E402, F401
import app.models.atlas_enterprise  # noqa: E402, F401
import app.models.nexus_integration  # noqa: E402, F401
import app.models.predictive_insight  # noqa: E402, F401
import app.models.federated_horizon  # noqa: E402, F401
import app.models.industry_collaboration  # noqa: E402, F401
import app.models.platform_core  # noqa: E402, F401
import app.models.workflow_forge  # noqa: E402, F401
import app.models.pulse_operations  # noqa: E402, F401
import app.models.catalyst_copilot  # noqa: E402, F401
import app.models.orbit_readiness  # noqa: E402, F401
import app.models.vanguard_intelligence  # noqa: E402, F401
import app.models.apollo_quality  # noqa: E402, F401
import app.models.athena_knowledge  # noqa: E402, F401
import app.models.phoenix_intelligence  # noqa: E402, F401
import app.models.infinity_platform  # noqa: E402, F401
import app.models.olympus_network  # noqa: E402, F401
import app.models.guardianx_assurance  # noqa: E402, F401
import app.models.genesis_ai_intelligence_cloud  # noqa: E402, F401
import app.models.nova_agent_platform  # noqa: E402, F401
import app.models.vulcan_reliability  # noqa: E402, F401
import app.models.sage_education  # noqa: E402, F401
import app.models.veritas_evidence  # noqa: E402, F401
import app.models.sentinelx_risk  # noqa: E402, F401
import app.models.maestro_orchestration  # noqa: E402, F401
import app.models.council_leadership  # noqa: E402, F401
import app.models.account_review_delivery  # noqa: E402, F401
import app.models.account_review_export  # noqa: E402, F401
import app.models.account_review_packet  # noqa: E402, F401
import app.models.admin_credential  # noqa: E402, F401
import app.models.automation_rule  # noqa: E402, F401
import app.models.automation_run  # noqa: E402, F401
import app.models.capture_device  # noqa: E402, F401
import app.models.competency_event  # noqa: E402, F401
import app.models.continuous_improvement  # noqa: E402, F401
import app.models.customer_health_snapshot  # noqa: E402, F401
import app.models.customer_success_playbook  # noqa: E402, F401
import app.models.digest_delivery  # noqa: E402, F401
import app.models.digest_subscription  # noqa: E402, F401
import app.models.disposition_override  # noqa: E402, F401
import app.models.distribution_list  # noqa: E402, F401
import app.models.distribution_recipient  # noqa: E402, F401
import app.models.executive_scorecard  # noqa: E402, F401
import app.models.feature_flag  # noqa: E402, F401
import app.models.generated_briefing  # noqa: E402, F401
import app.models.go_live_checkpoint  # noqa: E402, F401
import app.models.governance_approval  # noqa: E402, F401
import app.models.governance_rollback  # noqa: E402, F401
import app.models.implementation_readiness_item  # noqa: E402, F401
import app.models.inspection_finding  # noqa: E402, F401
import app.models.instrument_knowledge  # noqa: E402, F401
import app.models.invoice_line_item  # noqa: E402, F401
import app.models.knowledge  # noqa: E402, F401
import app.models.mentor_coaching_review  # noqa: E402, F401
import app.models.mobile  # noqa: E402, F401
import app.models.model_registry  # noqa: E402, F401
import app.models.notification_template  # noqa: E402, F401
import app.models.packet_release_history  # noqa: E402, F401
import app.models.pilot_config  # noqa: E402, F401
import app.models.pilot_error_log  # noqa: E402, F401
import app.models.portfolio_briefing  # noqa: E402, F401
import app.models.renewal_risk_case  # noqa: E402, F401
import app.models.report_run  # noqa: E402, F401
import app.models.retained_image  # noqa: E402, F401
import app.models.retention_event  # noqa: E402, F401
import app.models.root_cause  # noqa: E402, F401
import app.models.saved_report  # noqa: E402, F401
import app.models.scheduled_account_review  # noqa: E402, F401
import app.models.scheduled_leadership_packet  # noqa: E402, F401
import app.models.shadow_prediction  # noqa: E402, F401
import app.models.subscription_change_event  # noqa: E402, F401
import app.models.tenant_branding  # noqa: E402, F401
import app.models.tenant_entitlement  # noqa: E402, F401
import app.models.tenant_onboarding  # noqa: E402, F401
import app.models.tenant_quota  # noqa: E402, F401
import app.models.tenant_subscription  # noqa: E402, F401
import app.models.usage_event  # noqa: E402, F401
import app.models.user_role_assignment  # noqa: E402, F401
import app.models.vendor_baseline_audit  # noqa: E402, F401
import app.models.workflow  # noqa: E402, F401

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (no DB connection required, emit SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (with live DB connection)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
