from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas


def build_inspection_pdf(doc: dict) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, "LumenAI Inspection Report")

    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.25 * inch, "Generated by LumenAI MVP")

    y = height - 1.5 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Instrument Details")
    y -= 0.25 * inch

    c.setFont("Helvetica", 11)
    c.drawString(1 * inch, y, f"Instrument: {doc.get('instrument_name', '')}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Inspection ID: {doc.get('id', '')}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Timestamp: {doc.get('timestamp', '')}")
    y -= 0.5 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "AI Findings")
    y -= 0.25 * inch

    res = doc.get("results", {}) or {}

    c.setFont("Helvetica", 11)
    c.drawString(1 * inch, y, f"Material Type: {res.get('material_type', '')}")
    y -= 0.2 * inch

    stain_detected = "Yes" if res.get("stain_detected") else "No"
    c.drawString(1 * inch, y, f"Stain Detected: {stain_detected}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Confidence: {res.get('confidence', '')}")
    y -= 0.5 * inch

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        1 * inch,
        0.75 * inch,
        "© LumenAI — Automated Lumen Inspection • For clinical QA reference only",
    )

    c.showPage()
    c.save()

    pdf = buf.getvalue()
    buf.close()

    return pdf


def build_regulatory_audit_pdf(package: dict) -> bytes:
    """Generate a regulatory audit package PDF using ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter
    margin = 1 * inch
    y = height - margin

    # Header
    c.setFillColor(HexColor("#0f172a"))
    c.rect(0, height - 1.2 * inch, width, 1.2 * inch, fill=True, stroke=False)
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin, height - 0.5 * inch, "LumenAI Regulatory Audit Package")
    c.setFont("Helvetica", 10)
    c.drawString(margin, height - 0.75 * inch, f"{package.get('package_type', '').replace('_', ' ').title()} | {package.get('period_label', '')} | Generated: {package.get('generated_at', '')[:10]}")

    y = height - 1.5 * inch
    c.setFillColor(HexColor("#000000"))

    # Readiness score
    score = package.get("accreditation_score", 0)
    tier = package.get("readiness_tier", "")
    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y, f"Overall Readiness Score: {score}/100  [{tier.replace('_', ' ').upper()}]")
    y -= 0.3 * inch

    # Standards covered
    standards = package.get("standards_covered", [])
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, f"Standards Covered ({len(standards)}): {', '.join(standards[:6])}")
    y -= 0.4 * inch

    # Findings
    findings = package.get("findings", [])
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, f"Deficiency Findings ({len(findings)})")
    y -= 0.25 * inch
    c.setFont("Helvetica", 9)

    for f in findings[:15]:  # max 15 on page 1
        if y < 1.5 * inch:
            c.showPage()
            y = height - margin
            c.setFont("Helvetica", 9)
        sev_colors = {"critical": "#dc2626", "high": "#f97316", "medium": "#f59e0b", "low": "#6b7280"}
        sev_color = sev_colors.get(f.get("severity", "medium"), "#6b7280")
        c.setFillColor(HexColor(sev_color))
        c.drawString(margin, y, f"[{f.get('severity', '').upper()}]")
        c.setFillColor(HexColor("#000000"))
        c.drawString(margin + 0.8 * inch, y, f"{f.get('standard_code', '')} — {f.get('finding_category', '')} ({f.get('occurrence_count', 0)} occurrences, {f.get('rate_pct', 0)}%)")
        y -= 0.15 * inch
        c.setFont("Helvetica-Oblique", 8)
        remediation = f.get("remediation_guidance", "")[:120]
        c.drawString(margin + 0.2 * inch, y, remediation)
        c.setFont("Helvetica", 9)
        y -= 0.2 * inch

    # Recommended actions
    y -= 0.2 * inch
    if y < 2 * inch:
        c.showPage()
        y = height - margin
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Recommended Actions")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)
    for i, action in enumerate(package.get("recommended_actions", []), 1):
        if y < 1.2 * inch:
            c.showPage()
            y = height - margin
            c.setFont("Helvetica", 10)
        c.drawString(margin, y, f"{i}. {action[:110]}")
        y -= 0.2 * inch

    # Attestation footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(HexColor("#6b7280"))
    att = package.get("attestation", {})
    c.drawString(margin, 0.6 * inch, att.get("statement", "")[:120])
    c.drawString(margin, 0.4 * inch, f"Generated by: {att.get('generated_by', 'system')} | System: {att.get('system_version', 'P8')}")

    c.save()
    return buf.getvalue()
