from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


def build_inspection_pdf(doc: dict) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, "LumenAI Inspection Report")

    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.25 * inch, "Generated by LumenAI MVP")

    y = height - 1.5 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Instrument Details")
    y -= 0.25 * inch

    c.setFont("Helvetica", 11)
    c.drawString(1 * inch, y, f"Instrument: {doc.get('instrument_name', '')}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Inspection ID: {doc.get('id', '')}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Timestamp: {doc.get('timestamp', '')}")
    y -= 0.5 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "AI Findings")
    y -= 0.25 * inch

    res = doc.get("results", {}) or {}

    c.setFont("Helvetica", 11)
    c.drawString(1 * inch, y, f"Material Type: {res.get('material_type', '')}")
    y -= 0.2 * inch

    stain_detected = "Yes" if res.get("stain_detected") else "No"
    c.drawString(1 * inch, y, f"Stain Detected: {stain_detected}")
    y -= 0.2 * inch

    c.drawString(1 * inch, y, f"Confidence: {res.get('confidence', '')}")
    y -= 0.5 * inch

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        1 * inch,
        0.75 * inch,
        "© LumenAI — Automated Lumen Inspection • For clinical QA reference only",
    )

    c.showPage()
    c.save()

    pdf = buf.getvalue()
    buf.close()

    return pdf
