/**
 * Post-build step for the STANDALONE marketing site (`npm run build:site`).
 *
 * The marketing Vite config sets `publicDir: false` so the app's `public/`
 * directory is NOT copied wholesale — that directory contains unrelated static
 * demo pages (public/portfolio/*, public/dashboard/*) that embed internal
 * backend hostnames and would be published on the public marketing domain.
 *
 * This script assembles only what the marketing site actually serves:
 *   1. Renames the Vite entry  dist-site/marketing.html -> dist-site/index.html
 *      so it is served at the domain root.
 *   2. Injects the domain: replaces the `__SITE_ORIGIN__` placeholder in
 *      index.html with SITE_ORIGIN from marketing-seo/site.config.mjs (the
 *      single source of truth for the domain — canonical / og:url / images).
 *   3. Copies public/site/*  (social-card.svg, lumenai-explainer.vtt) ->
 *      dist-site/site/  — the only public assets the marketing pages reference.
 *   4. GENERATES dist-site/robots.txt and dist-site/sitemap.xml from
 *      SITE_ORIGIN + ROUTES — so the domain lives in exactly one place.
 *   5. Writes dist-site/_redirects (SPA catch-all for Netlify/Render/Cloudflare)
 *      and dist-site/404.html (SPA fallback for hosts that ignore _redirects,
 *      e.g. GitHub Pages).
 *
 * Single source of truth: the domain is defined ONLY in
 * frontend/marketing-seo/site.config.mjs.
 */
import { cp, rename, writeFile, readFile, readdir, copyFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SITE_ORIGIN, ROUTES } from "../marketing-seo/site.config.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const frontend = path.resolve(here, "..");
const publicDir = path.join(frontend, "public");
const distSite = path.join(frontend, "dist-site");

const origin = SITE_ORIGIN.replace(/\/+$/, ""); // no trailing slash

// 1. marketing.html -> index.html
const indexPath = path.join(distSite, "index.html");
await rename(path.join(distSite, "marketing.html"), indexPath);

// 2. Inject the domain into the canonical / og / twitter tags.
const html = await readFile(indexPath, "utf8");
await writeFile(indexPath, html.replaceAll("__SITE_ORIGIN__", origin), "utf8");

// 3. Copy only public/site/* (the marketing-referenced assets).
const publicSite = path.join(publicDir, "site");
if (existsSync(publicSite)) {
  await cp(publicSite, path.join(distSite, "site"), { recursive: true });
}

// 4. Generate robots.txt + sitemap.xml from the single source of truth.
await writeFile(
  path.join(distSite, "robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`,
  "utf8",
);

const urls = ROUTES.map(
  (r) =>
    `  <url><loc>${origin}${r.path}</loc><changefreq>monthly</changefreq>` +
    `<priority>${r.priority}</priority></url>`,
).join("\n");
await writeFile(
  path.join(distSite, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/postbuild-site.mjs from marketing-seo/site.config.mjs. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
  "utf8",
);

// 5. SPA fallbacks.
await writeFile(path.join(distSite, "_redirects"), "/*    /index.html    200\n", "utf8");
await copyFile(indexPath, path.join(distSite, "404.html"));

// Report what shipped so the build log makes the surface explicit.
const shipped = await readdir(distSite);
console.log(`[build:site] origin=${origin}`);
console.log(`[build:site] dist-site root: ${shipped.sort().join(", ")}`);
