"""add_oracle_discovery_tables_and_governance_knowledge_fix

Revision ID: a1ba6c5ed8f8
Revises: f29f1456bdec
Create Date: 2026-07-13 01:01:51.757648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ba6c5ed8f8'
down_revision: Union[str, None] = 'f29f1456bdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracle_digital_twin_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('facility_id', sa.String(length=100), nullable=False),
    sa.Column('source_service', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('insight_summary', sa.Text(), nullable=False),
    sa.Column('underlying_snapshot_json', sa.Text(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('promoted_to_hypothesis_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_digital_twin_insights_created_at'), 'oracle_digital_twin_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_digital_twin_insights_facility_id'), 'oracle_digital_twin_insights', ['facility_id'], unique=False)
    op.create_index(op.f('ix_oracle_digital_twin_insights_id'), 'oracle_digital_twin_insights', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_digital_twin_insights_promoted_to_hypothesis_id'), 'oracle_digital_twin_insights', ['promoted_to_hypothesis_id'], unique=False)
    op.create_index(op.f('ix_oracle_digital_twin_insights_source_service'), 'oracle_digital_twin_insights', ['source_service'], unique=False)
    op.create_index(op.f('ix_oracle_digital_twin_insights_tenant_id'), 'oracle_digital_twin_insights', ['tenant_id'], unique=False)
    op.create_table('oracle_hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('facility_id', sa.String(length=100), nullable=False),
    sa.Column('hypothesis_code', sa.String(length=50), nullable=False),
    sa.Column('discovery_category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('observation_summary', sa.Text(), nullable=False),
    sa.Column('hypothesis_statement', sa.Text(), nullable=False),
    sa.Column('supporting_literature_json', sa.Text(), nullable=False),
    sa.Column('related_instruments_json', sa.Text(), nullable=False),
    sa.Column('related_anatomy_json', sa.Text(), nullable=False),
    sa.Column('digital_twin_refs_json', sa.Text(), nullable=False),
    sa.Column('knowledge_links_json', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('statistical_summary_json', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=30), nullable=False),
    sa.Column('research_owner', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('outcome_summary', sa.Text(), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_hypotheses_created_at'), 'oracle_hypotheses', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_current_stage'), 'oracle_hypotheses', ['current_stage'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_discovery_category'), 'oracle_hypotheses', ['discovery_category'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_facility_id'), 'oracle_hypotheses', ['facility_id'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_hypothesis_code'), 'oracle_hypotheses', ['hypothesis_code'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_id'), 'oracle_hypotheses', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_research_owner'), 'oracle_hypotheses', ['research_owner'], unique=False)
    op.create_index(op.f('ix_oracle_hypotheses_tenant_id'), 'oracle_hypotheses', ['tenant_id'], unique=False)
    op.create_table('oracle_knowledge_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('suggested_article_title', sa.String(length=300), nullable=False),
    sa.Column('suggested_article_body', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('governance_approval_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_article_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_knowledge_suggestions_created_at'), 'oracle_knowledge_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_governance_approval_id'), 'oracle_knowledge_suggestions', ['governance_approval_id'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_hypothesis_id'), 'oracle_knowledge_suggestions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_id'), 'oracle_knowledge_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_knowledge_article_id'), 'oracle_knowledge_suggestions', ['knowledge_article_id'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_status'), 'oracle_knowledge_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_oracle_knowledge_suggestions_tenant_id'), 'oracle_knowledge_suggestions', ['tenant_id'], unique=False)
    op.create_table('oracle_model_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('model_scope', sa.String(length=100), nullable=False),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('ai_health_snapshot_json', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('promoted_to_hypothesis_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_model_observations_created_at'), 'oracle_model_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_model_observations_id'), 'oracle_model_observations', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_model_observations_observation_type'), 'oracle_model_observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_oracle_model_observations_promoted_to_hypothesis_id'), 'oracle_model_observations', ['promoted_to_hypothesis_id'], unique=False)
    op.create_index(op.f('ix_oracle_model_observations_tenant_id'), 'oracle_model_observations', ['tenant_id'], unique=False)
    op.create_table('oracle_stage_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=30), nullable=False),
    sa.Column('to_stage', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changed_by_role', sa.String(length=50), nullable=False),
    sa.Column('gate_check_notes', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_stage_transitions_created_at'), 'oracle_stage_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_stage_transitions_hypothesis_id'), 'oracle_stage_transitions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_oracle_stage_transitions_id'), 'oracle_stage_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_stage_transitions_tenant_id'), 'oracle_stage_transitions', ['tenant_id'], unique=False)
    op.create_table('oracle_trend_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('facility_id', sa.String(length=100), nullable=False),
    sa.Column('trend_category', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('observation_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_points_json', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('statistical_confidence', sa.String(length=20), nullable=False),
    sa.Column('promoted_to_hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oracle_trend_observations_created_at'), 'oracle_trend_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_oracle_trend_observations_facility_id'), 'oracle_trend_observations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_oracle_trend_observations_id'), 'oracle_trend_observations', ['id'], unique=False)
    op.create_index(op.f('ix_oracle_trend_observations_promoted_to_hypothesis_id'), 'oracle_trend_observations', ['promoted_to_hypothesis_id'], unique=False)
    op.create_index(op.f('ix_oracle_trend_observations_tenant_id'), 'oracle_trend_observations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_oracle_trend_observations_trend_category'), 'oracle_trend_observations', ['trend_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oracle_trend_observations_trend_category'), table_name='oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_trend_observations_tenant_id'), table_name='oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_trend_observations_promoted_to_hypothesis_id'), table_name='oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_trend_observations_id'), table_name='oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_trend_observations_facility_id'), table_name='oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_trend_observations_created_at'), table_name='oracle_trend_observations')
    op.drop_table('oracle_trend_observations')
    op.drop_index(op.f('ix_oracle_stage_transitions_tenant_id'), table_name='oracle_stage_transitions')
    op.drop_index(op.f('ix_oracle_stage_transitions_id'), table_name='oracle_stage_transitions')
    op.drop_index(op.f('ix_oracle_stage_transitions_hypothesis_id'), table_name='oracle_stage_transitions')
    op.drop_index(op.f('ix_oracle_stage_transitions_created_at'), table_name='oracle_stage_transitions')
    op.drop_table('oracle_stage_transitions')
    op.drop_index(op.f('ix_oracle_model_observations_tenant_id'), table_name='oracle_model_observations')
    op.drop_index(op.f('ix_oracle_model_observations_promoted_to_hypothesis_id'), table_name='oracle_model_observations')
    op.drop_index(op.f('ix_oracle_model_observations_observation_type'), table_name='oracle_model_observations')
    op.drop_index(op.f('ix_oracle_model_observations_id'), table_name='oracle_model_observations')
    op.drop_index(op.f('ix_oracle_model_observations_created_at'), table_name='oracle_model_observations')
    op.drop_table('oracle_model_observations')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_tenant_id'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_status'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_knowledge_article_id'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_id'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_hypothesis_id'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_governance_approval_id'), table_name='oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_knowledge_suggestions_created_at'), table_name='oracle_knowledge_suggestions')
    op.drop_table('oracle_knowledge_suggestions')
    op.drop_index(op.f('ix_oracle_hypotheses_tenant_id'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_research_owner'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_id'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_hypothesis_code'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_facility_id'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_discovery_category'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_current_stage'), table_name='oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_hypotheses_created_at'), table_name='oracle_hypotheses')
    op.drop_table('oracle_hypotheses')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_tenant_id'), table_name='oracle_digital_twin_insights')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_source_service'), table_name='oracle_digital_twin_insights')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_promoted_to_hypothesis_id'), table_name='oracle_digital_twin_insights')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_id'), table_name='oracle_digital_twin_insights')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_facility_id'), table_name='oracle_digital_twin_insights')
    op.drop_index(op.f('ix_oracle_digital_twin_insights_created_at'), table_name='oracle_digital_twin_insights')
    op.drop_table('oracle_digital_twin_insights')
    # ### end Alembic commands ###
