"""add_governed_action_tables

Revision ID: f29f1456bdec
Revises: 4b336d3ed612
Create Date: 2026-07-12 23:22:42.668175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29f1456bdec'
down_revision: Union[str, None] = '4b336d3ed612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governed_action_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changed_by_role', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_audit_events_created_at'), 'governed_action_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_audit_events_governed_action_id'), 'governed_action_audit_events', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_audit_events_id'), 'governed_action_audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_audit_events_tenant_id'), 'governed_action_audit_events', ['tenant_id'], unique=False)
    op.create_table('governed_action_outcome_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_outcome_reviews_created_at'), 'governed_action_outcome_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_outcome_reviews_governed_action_id'), 'governed_action_outcome_reviews', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_outcome_reviews_id'), 'governed_action_outcome_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_outcome_reviews_tenant_id'), 'governed_action_outcome_reviews', ['tenant_id'], unique=False)
    op.create_table('governed_action_residual_risk_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('risk_before', sa.Float(), nullable=True),
    sa.Column('risk_during', sa.Float(), nullable=True),
    sa.Column('risk_after', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_residual_risk_reviews_created_at'), 'governed_action_residual_risk_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_residual_risk_reviews_governed_action_id'), 'governed_action_residual_risk_reviews', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_residual_risk_reviews_id'), 'governed_action_residual_risk_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_residual_risk_reviews_tenant_id'), 'governed_action_residual_risk_reviews', ['tenant_id'], unique=False)
    op.create_table('governed_action_rollouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('rollout_scope', sa.String(length=30), nullable=False),
    sa.Column('scope_value', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_metrics_json', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=False),
    sa.Column('adverse_effects', sa.Text(), nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=False),
    sa.Column('go_no_go_decision', sa.String(length=20), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_rollouts_created_at'), 'governed_action_rollouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_rollouts_governed_action_id'), 'governed_action_rollouts', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_rollouts_id'), 'governed_action_rollouts', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_rollouts_tenant_id'), 'governed_action_rollouts', ['tenant_id'], unique=False)
    op.create_table('governed_action_unintended_consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('consequence_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_unintended_consequences_created_at'), 'governed_action_unintended_consequences', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_unintended_consequences_governed_action_id'), 'governed_action_unintended_consequences', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_unintended_consequences_id'), 'governed_action_unintended_consequences', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_unintended_consequences_tenant_id'), 'governed_action_unintended_consequences', ['tenant_id'], unique=False)
    op.create_table('governed_action_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('governed_action_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sufficient', sa.Boolean(), nullable=False),
    sa.Column('insufficiency_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_action_verifications_created_at'), 'governed_action_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_action_verifications_governed_action_id'), 'governed_action_verifications', ['governed_action_id'], unique=False)
    op.create_index(op.f('ix_governed_action_verifications_id'), 'governed_action_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_governed_action_verifications_tenant_id'), 'governed_action_verifications', ['tenant_id'], unique=False)
    op.create_table('governed_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('facility_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_decision', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approval_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_title', sa.String(length=300), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('accountable_leader', sa.String(length=255), nullable=False),
    sa.Column('stakeholders_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('milestones_json', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_requirements_json', sa.Text(), nullable=False),
    sa.Column('expected_outcomes', sa.Text(), nullable=False),
    sa.Column('success_metrics_json', sa.Text(), nullable=False),
    sa.Column('actual_outcomes', sa.Text(), nullable=False),
    sa.Column('benefits_realization', sa.String(length=30), nullable=False),
    sa.Column('unintended_consequences_json', sa.Text(), nullable=False),
    sa.Column('change_readiness', sa.String(length=30), nullable=False),
    sa.Column('closure_decision', sa.String(length=30), nullable=False),
    sa.Column('closure_approver', sa.String(length=255), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_actions_action_type'), 'governed_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_governed_actions_category'), 'governed_actions', ['category'], unique=False)
    op.create_index(op.f('ix_governed_actions_created_at'), 'governed_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_governed_actions_due_date'), 'governed_actions', ['due_date'], unique=False)
    op.create_index(op.f('ix_governed_actions_facility_id'), 'governed_actions', ['facility_id'], unique=False)
    op.create_index(op.f('ix_governed_actions_id'), 'governed_actions', ['id'], unique=False)
    op.create_index(op.f('ix_governed_actions_owner'), 'governed_actions', ['owner'], unique=False)
    op.create_index(op.f('ix_governed_actions_priority'), 'governed_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_governed_actions_risk_level'), 'governed_actions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_governed_actions_source_id'), 'governed_actions', ['source_id'], unique=False)
    op.create_index(op.f('ix_governed_actions_source_type'), 'governed_actions', ['source_type'], unique=False)
    op.create_index(op.f('ix_governed_actions_status'), 'governed_actions', ['status'], unique=False)
    op.create_index(op.f('ix_governed_actions_tenant_id'), 'governed_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governed_actions_tenant_id'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_status'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_source_type'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_source_id'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_risk_level'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_priority'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_owner'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_id'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_facility_id'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_due_date'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_created_at'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_category'), table_name='governed_actions')
    op.drop_index(op.f('ix_governed_actions_action_type'), table_name='governed_actions')
    op.drop_table('governed_actions')
    op.drop_index(op.f('ix_governed_action_verifications_tenant_id'), table_name='governed_action_verifications')
    op.drop_index(op.f('ix_governed_action_verifications_id'), table_name='governed_action_verifications')
    op.drop_index(op.f('ix_governed_action_verifications_governed_action_id'), table_name='governed_action_verifications')
    op.drop_index(op.f('ix_governed_action_verifications_created_at'), table_name='governed_action_verifications')
    op.drop_table('governed_action_verifications')
    op.drop_index(op.f('ix_governed_action_unintended_consequences_tenant_id'), table_name='governed_action_unintended_consequences')
    op.drop_index(op.f('ix_governed_action_unintended_consequences_id'), table_name='governed_action_unintended_consequences')
    op.drop_index(op.f('ix_governed_action_unintended_consequences_governed_action_id'), table_name='governed_action_unintended_consequences')
    op.drop_index(op.f('ix_governed_action_unintended_consequences_created_at'), table_name='governed_action_unintended_consequences')
    op.drop_table('governed_action_unintended_consequences')
    op.drop_index(op.f('ix_governed_action_rollouts_tenant_id'), table_name='governed_action_rollouts')
    op.drop_index(op.f('ix_governed_action_rollouts_id'), table_name='governed_action_rollouts')
    op.drop_index(op.f('ix_governed_action_rollouts_governed_action_id'), table_name='governed_action_rollouts')
    op.drop_index(op.f('ix_governed_action_rollouts_created_at'), table_name='governed_action_rollouts')
    op.drop_table('governed_action_rollouts')
    op.drop_index(op.f('ix_governed_action_residual_risk_reviews_tenant_id'), table_name='governed_action_residual_risk_reviews')
    op.drop_index(op.f('ix_governed_action_residual_risk_reviews_id'), table_name='governed_action_residual_risk_reviews')
    op.drop_index(op.f('ix_governed_action_residual_risk_reviews_governed_action_id'), table_name='governed_action_residual_risk_reviews')
    op.drop_index(op.f('ix_governed_action_residual_risk_reviews_created_at'), table_name='governed_action_residual_risk_reviews')
    op.drop_table('governed_action_residual_risk_reviews')
    op.drop_index(op.f('ix_governed_action_outcome_reviews_tenant_id'), table_name='governed_action_outcome_reviews')
    op.drop_index(op.f('ix_governed_action_outcome_reviews_id'), table_name='governed_action_outcome_reviews')
    op.drop_index(op.f('ix_governed_action_outcome_reviews_governed_action_id'), table_name='governed_action_outcome_reviews')
    op.drop_index(op.f('ix_governed_action_outcome_reviews_created_at'), table_name='governed_action_outcome_reviews')
    op.drop_table('governed_action_outcome_reviews')
    op.drop_index(op.f('ix_governed_action_audit_events_tenant_id'), table_name='governed_action_audit_events')
    op.drop_index(op.f('ix_governed_action_audit_events_id'), table_name='governed_action_audit_events')
    op.drop_index(op.f('ix_governed_action_audit_events_governed_action_id'), table_name='governed_action_audit_events')
    op.drop_index(op.f('ix_governed_action_audit_events_created_at'), table_name='governed_action_audit_events')
    op.drop_table('governed_action_audit_events')
    # ### end Alembic commands ###
