"""P8: Regulatory & Accreditation Automation API routes."""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query, Request
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.deps import get_db
from app.enterprise_auth import require_enterprise_auth
from app.schemas.regulatory import AuditPackageRequest, FDASubmissionCreate
from app.services.accreditation_engine import (
    compute_accreditation_readiness,
    compute_regulatory_dashboard,
    generate_audit_package,
    list_fda_submissions,
    map_finding_to_clauses,
)
from app.tier_guard import require_tier

router = APIRouter(prefix="/api/regulatory", tags=["regulatory"])


@router.get("/readiness")
def accreditation_readiness(
    request: Request,
    tenant_id: str = Query(...),
    facility_id: str = Query(default=""),
    db: Session = Depends(get_db),
):
    """Real-time accreditation readiness score across all regulatory bodies."""
    require_enterprise_auth(request)
    require_tier(tenant_id, "regulatory_readiness", db)
    result = compute_accreditation_readiness(tenant_id, facility_id, db)
    return {"status": "success", "readiness": result.model_dump()}


@router.get("/readiness/findings")
def readiness_findings(
    request: Request,
    tenant_id: str = Query(...),
    facility_id: str = Query(default=""),
    severity: str = Query(default=""),
    db: Session = Depends(get_db),
):
    """List all accreditation deficiency findings, optionally filtered by severity."""
    require_enterprise_auth(request)
    require_tier(tenant_id, "regulatory_findings", db)
    result = compute_accreditation_readiness(tenant_id, facility_id, db)
    findings = result.findings
    if severity:
        findings = [f for f in findings if f.severity == severity]
    return {
        "status": "success",
        "total": len(findings),
        "findings": [f.model_dump() for f in findings],
    }


@router.get("/standards")
def list_standards(
    request: Request,
    body: str = Query(default=""),
    category: str = Query(default=""),
):
    """List all regulatory standards in the catalogue."""
    require_enterprise_auth(request)
    from app.services.regulatory_standards_catalogue import get_standards
    stds = get_standards()
    if body:
        stds = [s for s in stds if s.body == body]
    if category:
        stds = [s for s in stds if s.category == category]
    return {
        "status": "success",
        "standards": [
            {"code": s.code, "body": s.body, "title": s.title,
             "description": s.description, "category": s.category}
            for s in stds
        ],
    }


@router.get("/standards/mapping")
def finding_clause_mapping(
    request: Request,
    finding_category: str = Query(...),
    severity: str = Query(default="any"),
):
    """Map a CV finding category to triggered regulatory clauses."""
    require_enterprise_auth(request)
    clauses = map_finding_to_clauses(finding_category, severity)
    return {
        "status": "success",
        "finding_category": finding_category,
        "clauses": clauses,
    }


@router.post("/audit-package")
def create_audit_package(
    body: AuditPackageRequest,
    request: Request,
    db: Session = Depends(get_db),
):
    """Generate an audit-ready evidence package for a regulatory body."""
    require_enterprise_auth(request)
    require_tier(body.tenant_id, "audit_package", db)
    package = generate_audit_package(
        tenant_id=body.tenant_id,
        facility_id=body.facility_id,
        package_type=body.package_type,
        period_label=body.period_label,
        generated_by=body.generated_by,
        db=db,
    )
    return {"status": "success", "package": package.model_dump()}


@router.post("/audit-package/pdf")
def download_audit_package_pdf(
    body: AuditPackageRequest,
    request: Request,
    db: Session = Depends(get_db),
):
    """Generate and download a regulatory audit package as PDF."""
    require_enterprise_auth(request)
    require_tier(body.tenant_id, "audit_package", db)
    from app.services.report_pdf import build_regulatory_audit_pdf
    package = generate_audit_package(
        tenant_id=body.tenant_id,
        facility_id=body.facility_id,
        package_type=body.package_type,
        period_label=body.period_label,
        generated_by=body.generated_by,
        db=db,
    )
    pkg_dict = package.model_dump()
    pkg_dict["attestation"] = {
        "statement": f"Auto-generated by LumenAI on {package.generated_at}. Findings derived from AI-assisted inspection records.",
        "generated_by": package.generated_by,
        "system_version": "P8.1",
    }
    pdf_bytes = build_regulatory_audit_pdf(pkg_dict)
    filename = f"lumenai-audit-{body.package_type}-{package.period_label}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/audit-packages")
def list_audit_packages(
    request: Request,
    tenant_id: str = Query(...),
    db: Session = Depends(get_db),
):
    """List previously generated audit packages for a tenant."""
    require_enterprise_auth(request)
    require_tier(tenant_id, "audit_package", db)
    try:
        from app.models.regulatory import RegulatoryAuditPackage
        rows = db.query(RegulatoryAuditPackage).filter_by(tenant_id=tenant_id)\
            .order_by(RegulatoryAuditPackage.created_at.desc()).limit(20).all()
        packages = [
            {
                "id": r.id, "package_type": r.package_type, "period_label": r.period_label,
                "status": r.status, "findings_count": r.findings_count,
                "created_at": r.created_at.isoformat(),
            }
            for r in rows
        ]
    except Exception:
        packages = []
    return {"status": "success", "packages": packages}


@router.get("/fda-submissions")
def get_fda_submissions(
    request: Request,
    tenant_id: str = Query(...),
    db: Session = Depends(get_db),
):
    """List FDA submission tracking records.

    submissions is only ever populated from real FDASubmissionTracker rows --
    never fabricated. is_synthetic is always False for that reason;
    data_available reports whether any real record was found.
    """
    require_enterprise_auth(request)
    require_tier(tenant_id, "fda_tracking", db)
    submissions = list_fda_submissions(tenant_id, db)
    return {
        "status": "success",
        "submissions": [s.model_dump() for s in submissions],
        "is_synthetic": False,
        "data_available": bool(submissions),
    }


@router.post("/fda-submissions")
def create_fda_submission(
    body: FDASubmissionCreate,
    request: Request,
    db: Session = Depends(get_db),
):
    """Create an FDA submission tracking record."""
    require_enterprise_auth(request)
    require_tier(body.tenant_id, "fda_tracking", db)
    try:
        from app.models.regulatory import FDASubmissionTracker
        from datetime import datetime
        record = FDASubmissionTracker(
            tenant_id=body.tenant_id,
            submission_type=body.submission_type,
            submission_number=body.submission_number,
            device_name=body.device_name,
            manufacturer=body.manufacturer,
            status=body.status,
            submission_date=datetime.fromisoformat(body.submission_date) if body.submission_date else None,
            notes=body.notes,
        )
        db.add(record)
        db.commit()
        db.refresh(record)
        return {"status": "success", "id": record.id}
    except Exception:
        raise


@router.get("/dashboard")
def regulatory_dashboard(
    request: Request,
    tenant_id: str = Query(...),
    facility_id: str = Query(default=""),
    db: Session = Depends(get_db),
):
    """Executive regulatory compliance dashboard."""
    require_enterprise_auth(request)
    require_tier(tenant_id, "regulatory_dashboard", db)
    dashboard = compute_regulatory_dashboard(tenant_id, facility_id, db)
    return {"status": "success", "dashboard": dashboard.model_dump()}
