import os
from pathlib import Path

REPORTS_DIR = Path(os.getenv("REPORT_DIR", "./reports"))
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def _safe_filename(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in value.strip())
    return cleaned or "unknown"


def generate_vendor_scorecard_pdf(scorecard: dict) -> str:
    vendor_name = scorecard.get("vendor_name", "unknown")
    filename = f"vendor_scorecard_{_safe_filename(vendor_name)}.pdf"
    file_path = REPORTS_DIR / filename

    c = canvas.Canvas(str(file_path), pagesize=letter)
    width, height = letter

    y = height - 50
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "LumenAI Vendor Scorecard")
    y -= 28

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, f"Vendor: {vendor_name}")
    y -= 24

    c.setFont("Helvetica", 11)
    lines = [
        f"Total Inspections: {scorecard.get('total_inspections', 0)}",
        f"Escalations: {scorecard.get('escalations', 0)}",
        f"High Risk Count: {scorecard.get('high_risk_count', 0)}",
        f"Average Confidence: {scorecard.get('avg_confidence', 0.0)}",
        f"Latest Issue: {scorecard.get('latest_issue', 'unknown')}",
    ]

    for line in lines:
        c.drawString(50, y, line)
        y -= 18

    y -= 10
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Top Issues")
    y -= 20

    c.setFont("Helvetica", 11)
    top_issues = scorecard.get("top_issues", [])
    if not top_issues:
        c.drawString(50, y, "No issue data available.")
    else:
        for item in top_issues:
            c.drawString(60, y, f"- {item.get('label', 'unknown')}: {item.get('count', 0)}")
            y -= 18

    y -= 10
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        50,
        y,
        "Generated by LumenAI for vendor quality intelligence, SPD review, and executive analytics.",
    )

    c.save()
    return str(file_path)
