#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"
TOKEN="${TOKEN:-dev-token}"
ROLE="${ROLE:-enterprise_admin}"
ACTOR="${ACTOR:-demo-compliance-admin}"
TENANT_ID="${TENANT_ID:-demo-compliance-tenant}"
ACTION_TYPE="${ACTION_TYPE:-compliance_evidence_bundle_demo}"
RESOURCE_TYPE="${RESOURCE_TYPE:-demo_compliance_resource}"
RESOURCE_ID="${RESOURCE_ID:-demo-resource-001}"

AUTH_HEADERS=(
  -H "Authorization: Bearer ${TOKEN}"
  -H "X-LumenAI-Role: ${ROLE}"
  -H "X-LumenAI-Actor: ${ACTOR}"
  -H "X-LumenAI-Tenant-ID: ${TENANT_ID}"
  -H "X-Request-ID: demo-request-001"
  -H "X-Correlation-ID: demo-correlation-001"
)

echo
echo "== LumenAI Compliance Evidence Bundle Demo =="
echo "Base URL: ${BASE_URL}"
echo "Tenant:   ${TENANT_ID}"
echo

echo "1) Creating demo audit event..."
curl -sS -X POST "${BASE_URL}/api/enterprise/audit/events" \
  "${AUTH_HEADERS[@]}" \
  -H "Content-Type: application/json" \
  -d "{
    \"action_type\": \"${ACTION_TYPE}\",
    \"resource_type\": \"${RESOURCE_TYPE}\",
    \"resource_id\": \"${RESOURCE_ID}\",
    \"details\": {
      \"workflow\": \"compliance-evidence-bundle-demo\",
      \"demo\": true
    }
  }" >/tmp/lumenai_demo_audit_event.json || true

echo "   Demo event request submitted."
echo

echo "2) Generating compliance evidence bundle..."
curl -sS -G "${BASE_URL}/api/enterprise/audit/evidence-bundle" \
  "${AUTH_HEADERS[@]}" \
  --data-urlencode "tenant_id=${TENANT_ID}" \
  --data-urlencode "action_type=${ACTION_TYPE}" \
  --data-urlencode "limit=200" \
  -o /tmp/lumenai_compliance_bundle_response.json

python - <<'PY'
import json
from pathlib import Path

path = Path("/tmp/lumenai_compliance_bundle_response.json")
payload = json.loads(path.read_text())

bundle_hash = payload.get("bundle_hash", "")
bundle = payload.get("bundle", {})
audit_export = bundle.get("audit_export", {})
manifest = bundle.get("manifest", {})

print(f"   Bundle hash:      {bundle_hash}")
print(f"   Bundle algorithm: {payload.get('bundle_hash_algorithm', '')}")
print(f"   Bundle event ID:  {payload.get('bundle_event_id', '')}")
print(f"   Audit export hash:{audit_export.get('audit_export_hash', '')}")
print(f"   Manifest hash:    {manifest.get('manifest_hash', '')}")
print(f"   Export count:     {audit_export.get('count', '')}")

Path("/tmp/lumenai_bundle_hash.txt").write_text(bundle_hash)
PY

BUNDLE_HASH="$(cat /tmp/lumenai_bundle_hash.txt)"

if [[ -z "${BUNDLE_HASH}" || "${BUNDLE_HASH}" == "None" ]]; then
  echo "ERROR: Bundle hash was not generated."
  cat /tmp/lumenai_compliance_bundle_response.json
  exit 1
fi

echo

echo "3) Verifying bundle hash..."
curl -sS -G "${BASE_URL}/api/enterprise/audit/evidence-bundle/verify" \
  "${AUTH_HEADERS[@]}" \
  --data-urlencode "bundle_hash=${BUNDLE_HASH}" \
  -o /tmp/lumenai_bundle_verify.json

python - <<'PY'
import json
from pathlib import Path

payload = json.loads(Path("/tmp/lumenai_bundle_verify.json").read_text())
print(f"   Verified:     {payload.get('verified')}")
print(f"   Message:      {payload.get('message')}")
print(f"   Event ID:     {payload.get('event_id')}")
print(f"   Export hash:  {payload.get('audit_export_hash')}")
print(f"   Manifest hash:{payload.get('manifest_hash')}")
PY

echo

echo "4) Loading public verification summary..."
curl -sS -G "${BASE_URL}/api/enterprise/audit/evidence-bundle/verification-summary" \
  "${AUTH_HEADERS[@]}" \
  --data-urlencode "bundle_hash=${BUNDLE_HASH}" \
  -o /tmp/lumenai_bundle_summary.json

python - <<'PY'
import json
from pathlib import Path

payload = json.loads(Path("/tmp/lumenai_bundle_summary.json").read_text())
print(f"   Summary type:  {payload.get('summary_type')}")
print(f"   Verified:      {payload.get('verified')}")
print(f"   Tamper evident:{payload.get('tamper_evident')}")
print(f"   Generated by:  {payload.get('generated_by')}")
print(f"   Generated at:  {payload.get('generated_at')}")
print(f"   Controls:      {', '.join(payload.get('compliance_controls', []))}")
PY

echo

echo "5) Downloading evidence bundle JSON artifact..."
curl -sS -G "${BASE_URL}/api/enterprise/audit/evidence-bundle/download.json" \
  "${AUTH_HEADERS[@]}" \
  --data-urlencode "tenant_id=${TENANT_ID}" \
  --data-urlencode "action_type=${ACTION_TYPE}" \
  --data-urlencode "limit=200" \
  -D /tmp/lumenai_bundle_download_headers.txt \
  -o /tmp/lumenai-compliance-evidence-bundle.json

echo "   Saved JSON artifact: /tmp/lumenai-compliance-evidence-bundle.json"
echo "   Saved headers:       /tmp/lumenai_bundle_download_headers.txt"

echo
echo "== Demo complete =="
